name: Remote Repo CI

on:
  push:
    branches:
      - master

jobs:
  make_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Repo
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug
          
      - name: Deploy to Repo Branch
        run: |
          git config --global user.email "mugi@manga.com"
          git config --global user.name "Mugi473"
          mkdir -p repo
          cp app/build/outputs/apk/debug/*.apk repo/
          cd repo
          # Le robot crée l'index indispensable pour Tachimanga
          echo "{\"name\":\"Mugi-Extensions\",\"author\":\"Mugi473\",\"extensions\":[]}" > index.min.json 
          git checkout -b repo || git checkout repo
          git add .
          git commit -m "Update repo"
          git push -f origin repo
